name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
       node-version: 24
       cache: 'npm'
    - run: npm install
    - name: Setup Pulsar Editor
      uses: pulsar-edit/action-pulsar-dependency@v3.4
    - name: Run the headless Pulsar Tests
      uses: mgor/setup-xvfb@592ebcbb2072ba2dfb7c1f12e686a7cf0fa413e5 # v1
      with:
        run: pulsar --test spec
